pipeline {
      agent any
      tools {
          nodejs "NodeJS 12"
      }
      stages {
          stage('Checkout') {
              steps {
                  git branch: 'master',
                      url: 'https://gitlab.com/assistiverobot/assistiverobot.web.application.git'
                  echo 'Checkout complete'
              }
          }
          stage('Deploy Web App') {
              steps {
                  bat 'appcmd stop apppool /apppool.name:\"Toktak Web App\"'
                  bat 'npm install'
                  bat 'npm run ng -- build --prod --outputPath=D:\\Toktak-Web-App\\website\\production --base-href /app/'
                  bat 'appcmd start apppool /apppool.name:\"Toktak Web App\"'
              }
          }
      }
}
